InventoryMgr/Controllers/InventoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;
using InventoryMgr.Filters;
using InventoryMgr.Models.Abstract;
using InventoryMgr.Models;
using AutoMapper;
using InventoryMgr.Models.ViewModels;

namespace InventoryMgr.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class InventoryController : Controller
    {
        private ICategoriesRepository _catRepos { get; set; }
        private IQtyMeasurementsRepository _qtyMeasurementsRepos { get; set; }
        private IInventoryRepository _inventoryRepos { get; set; }

        public InventoryController(ICategoriesRepository catsRepo,
            IQtyMeasurementsRepository qrepo,
            IInventoryRepository invRepos)
        {
            _catRepos = catsRepo;
            _qtyMeasurementsRepos = qrepo;
            _inventoryRepos = invRepos;
        }
        //
        // GET: /Inventory/
        public ActionResult Index()
        {
            int userId = WebSecurity.CurrentUserId;
            ViewBag.UserId = userId;
            //ViewBag.Categories = _catRepos.GetAll(userId).ToSelectListItems();
            //ViewBag.Measurements = _qtyMeasurementsRepos.GetAll(userId).ToSelectListItems();
            ViewBag.Title = "My Inventory";
            return View();
        }

        //
        //GET: /Inventory/Create
        public ActionResult Create() {
            int userId = WebSecurity.CurrentUserId;
            ViewBag.UserId = userId;
            ViewBag.Categories = _catRepos.GetAll(userId).ToSelectListItems();
            ViewBag.Measurements = _qtyMeasurementsRepos.GetAll(userId).ToSelectListItems();
            return PartialView("_Create", new InventoryItem());
        }

        //
        //Get: /Inventory/Edit/id 
        public ActionResult Edit(int Id)
        {           
            var invItem = _inventoryRepos.Get(Id);
            InventoryItemEditModel editModel = Mapper.Map<InventoryItem, InventoryItemEditModel>(invItem);
            //editModel.CategoryId = invItem.InventoryCategory.Id;
            //editModel.MeasurementsId = invItem.InventoryQtyMeasurements.Id;
            editModel.CategoryList = _catRepos.GetAll(invItem.UserId).ToSelectListItems(invItem.InventoryCategory.Id);
            editModel.MeasurementsList = _qtyMeasurementsRepos.GetAll(invItem.UserId).ToSelectListItems(invItem.InventoryQtyMeasurements.Id);


            //View with a View Model
            return PartialView("_Edit", editModel);
            
            //View without a View Model
            //return PartialView("_Edit", invItem);
        }

    }
}

InventoryMgr/Controllers/TaskListController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using InventoryMgr.Models;
using InventoryMgr.Filters;
using WebMatrix.WebData;
using InventoryMgr.Models.Abstract;

namespace InventoryMgr.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class TaskListController : Controller
    {
        private ITaskListRepository _tlRepo { get; set; }

        public TaskListController(ITaskListRepository iTLRepo)
        {
            _tlRepo = iTLRepo;
        }

        //
        // GET: /TaskList/

        public ActionResult Index()
        {
            int userId = WebSecurity.CurrentUserId;
            ViewBag.UserId = userId;
            ViewBag.Title = "My Task Lists";
            return View();
        }

        //
        // GET: /TaskList/Create

        public ActionResult Create()
        {
            return PartialView("_Create");
        }


        //
        // GET: /TaskList/Edit/5

        public ActionResult Edit(int id)
        {
            TaskList tasklist = _tlRepo.Get(id);
            if (tasklist == null)
            {
                return HttpNotFound();
            }
            return PartialView("_Edit", tasklist);
        }
    }
}

InventoryMgr/Views/Shared/_CreateCategory.cshtml
@model InventoryMgr.Models.InventoryCategory

<h2>Add New Inventory Category</h2>
@using (Html.BeginForm("", "api/Category", FormMethod.Post, new { id = "frmCreateCategory", @data_bind = "submit: createCategory" })) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>InventoryCategory</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.CategoryName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CategoryName)
            @Html.ValidationMessageFor(model => model.CategoryName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CategoryDescription)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CategoryDescription)
            @Html.ValidationMessageFor(model => model.CategoryDescription)
        </div>

        <input type="hidden" id="UserId" name="UserId" value="@ViewBag.UserId" />
        <input type="hidden" id="IsGlobal" name="IsGlobal" value="false" />

        <p>
            <input type="submit" value="Create" />
            <input type="button" value="Cancel" id="btnCancelCategoryCreate" />
        </p>
    </fieldset>
}

InventoryMgr/Views/Shared/_CreateQtyMeasurement.cshtml
@model InventoryMgr.Models.InventoryQtyMeasurements

@using (Html.BeginForm("", "api/Measurements", FormMethod.Post, new { id = "frmCreateMeasurement", @data_bind = "submit: createMeasurement" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>InventoryQtyMeasurements</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.UnitOfMeasure)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UnitOfMeasure)
            @Html.ValidationMessageFor(model => model.UnitOfMeasure)
        </div>
        
        <input type="hidden" id="UserId" name="UserId" value="@ViewBag.UserId" />
        <input type="hidden" id="IsGlobal" name="IsGlobal" value="false" />
        
        <p>
            <input type="submit" value="Create" />
            <input type="button" value="Cancel" id="btnCancelQtyMeasurementCreate" />
        </p>
    </fieldset>
}

InventoryMgr/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title"><a href="@Url.Action("Index", "Home")"><img class="bRadLogo" alt="B-Rad Logo" src="../../Images/B-Rad Logo.gif" BORDER=0 /></a></p>
                    <p class="site-title site-title-text">Inventory Management</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("My Inventory", "Index", "Inventory")</li>
                            <li>@Html.ActionLink("My Task Lists", "Index", "TaskList")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left" style="width:100%;">
                    <p>&copy; @DateTime.Now.Year - Bradley D. Gore</p><img alt="B-Rad Logo" src="../../Images/B-Rad Logo.gif" />
                </div>
                <div class="clear-fix"></div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>